import express from "express";
import cors from "cors";
import healthRoute from "./routes/health.route";
import weatherRoute from "./routes/weather.route";
import observationRoute from "./routes/observation.route";
import astronomyRoutes from "./routes/astronomy.routes";
import lightPollutionRoute from "./routes/lightpollution.routes";
import satelliteRoute from "./routes/satellite.routes";
import tleRoute from "./routes/tle.routes";
import celestialRoute from "./routes/celestial.routes";
import n2yoRoute from "./routes/n2yo.routes";
import dotenv from "dotenv";
dotenv.config();
import timelineRoute from "./routes/timeline.routes";
import aiRoute from "./routes/ai.routes";

const app = express();
app.use("/api/ai", aiRoute);

app.use(cors());
app.use(express.json());
app.use("/api/health", healthRoute);
app.use("/api/weather", weatherRoute);
app.use("/api/observation", observationRoute);
app.use("/api/astronomy", astronomyRoutes);
app.use("/api/lightpollution", lightPollutionRoute);
app.use("/api/satellite", satelliteRoute);
app.use("/api/tle", tleRoute);
app.use("/api/celestial", celestialRoute);
app.use("/api/n2yo", n2yoRoute);
app.use("/api/timeline", timelineRoute);
export default app;